'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("proyecto_contbilidad.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _13784() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("13784", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1600() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1600", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1600__1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1600 (1)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1Logo_Moxos_Wheels() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1Logo-Moxos-Wheels", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1Logo_Moxos_Wheels1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1Logo-Moxos-Wheels1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1YR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1YR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _2015_fiat_abarth_595_trofeo_edition_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2015_fiat_abarth_595_trofeo_edition_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _2016_Porsche_911_Gallery4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2016-Porsche-911-Gallery4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _2016_Porsche_911_Gallery41() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2016-Porsche-911-Gallery41", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3floppy_guardar_el_desmantelamiento_icono_4124_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3floppy-guardar-el-desmantelamiento-icono-4124-64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _4162521_orig() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("4162521_orig", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _687() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("687", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ac() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ac", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ac1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ac1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ad___copia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ad - copia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property arrow_left_15601() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow_left_15601", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property at() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("at", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property beos_carpeta_consultas_icono_7547_128() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("beos-carpeta-consultas-icono-7547-128", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property beos_carpeta_consultas_icono_7547_64_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("beos-carpeta-consultas-icono-7547-64-1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bmw_autos_usados_venta() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmw-autos-usados-venta", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property book_keeping_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("book_keeping-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property boton_de_anadir_mas_icono_6258_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("boton-de-anadir-mas-icono-6258-64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property boton_de_cancelacion_de_icono_7349_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("boton-de-cancelacion-de-icono-7349-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property calculadora_de_matematicas_icono_5680_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("calculadora-de-matematicas-icono-5680-48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property calcuworld() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("calcuworld", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ce() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ce", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property co() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("co", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property color_blanco() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("color-blanco", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property consultoria_contable_fiscal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("consultoria-contable-fiscal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cuadros_malla_luz_rojo_negro_Fondos_de_Pantalla_HD_professor_falken_com_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cuadros-malla-luz-rojo-negro-Fondos-de-Pantalla-HD-professor-falken.com_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cuadros_malla_luz_rojo_negro_Fondos_de_Pantalla_HD_professor_falken1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cuadros-malla-luz-rojo-negro-Fondos-de-Pantalla-HD-professor-falken1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cuadros_malla_luz_rojo_negro_Fondos_de_Pantalla_HD_professor_falken2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cuadros-malla-luz-rojo-negro-Fondos-de-Pantalla-HD-professor-falken2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cuadros_malla_luz_rojo_negro_Fondos_de_Pantalla_HD_professor_falken3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cuadros-malla-luz-rojo-negro-Fondos-de-Pantalla-HD-professor-falken3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cuadros_malla_luz_rojo_negro_Fondos_de_Pantalla_HD_professor_falken4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cuadros-malla-luz-rojo-negro-Fondos-de-Pantalla-HD-professor-falken4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cv() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cv", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property delete_button_icon_icons_com_71693() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("delete-button_icon-icons.com_71693", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property delete_button_icon_icons1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("delete-button_icon-icons1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property eduquese_en_seguridad_digital() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("eduquese-en-seguridad-digital", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property f22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("f22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property folder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property folder_library() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder-library", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property folder_locked() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder-locked", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property folder1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property folder2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property folder3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hoja_de_calculo_excel_invoice_icono_5449_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hoja-de-calculo-excel-invoice-icono-5449-64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property images() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imas() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imas", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imcre() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imcre", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imcruz_port() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imcruz port", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property impor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("impor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property impor1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("impor1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property inicio() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("inicio", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iStock_000077662959_Small() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iStock_000077662959_Small", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Izquierda_6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Izquierda-6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property la_lucha_contra_la_caja_registradora_icono_4028_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("la-lucha-contra-la-caja-registradora-icono-4028-64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property marca() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("marca", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property marcas_de_autos_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("marcas-de-autos-4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MARCAS_EN_TEKAUTO() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MARCAS EN TEKAUTO", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mimcruz() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mimcruz", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mis_cuentas_claras() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mis-cuentas-claras", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mis_cuentas_claras1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mis-cuentas-claras1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ok_dialogo_icono_8741_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ok-dialogo-icono-8741-64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property porsche_carrera_4_type_991_19() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("porsche-carrera-4-type-991-19", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PORSCHE911TurboS_997__4328_5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PORSCHE911TurboS-997--4328_5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property principal_jpgED() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("principal.jpgED", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property q() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("q", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TheMasterPro98__101_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TheMasterPro98 (101)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property verificacion_verde_ok_si_icono_8667_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("verificacion-verde-ok-si-icono-8667-48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property vidrios_en_los_libros_29014676___copia__2_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("vidrios-en-los-libros-29014676 - copia (2)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Windows_7_ultimate_collection_of_wallpapers_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Windows 7 ultimate collection of wallpapers.24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Windows_7_ultimate_collection_of_wallpapers1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Windows 7 ultimate collection of wallpapers1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property zotqbfue4eyhyyirwozy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("zotqbfue4eyhyyirwozy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property zotqbfue4eyhyyirwozy1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("zotqbfue4eyhyyirwozy1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property zotqbfue4eyhyyirwozy2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("zotqbfue4eyhyyirwozy2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
